title: Matthew Waas, PhD # your name (or website title) here
logo: "/images/Untitled-1.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Proteomics researcher and platform builder with a focus on cell surface biology.
 <br><br>
 Research Manager, Gundry Laboratory 
 Director, Bioassay Core, Center for Heart & Vascular Research
 <br><br>
  Universtiy of Nebraska Medical Center
  <br><br>
  <a href="https://www.linkedin.com/in/matthew-waas-phd-b78ba011b/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://scholar.google.com/citations?user=dTr6UNQAAAAJ&hl=en/">View My Google Scholar</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
